/*
 * generated by Xtext 2.30.0
 */
package org.thu.statemachine.textual.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.thu.statemachine.textual.SMDSLRuntimeModule;
import org.thu.statemachine.textual.SMDSLStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class SMDSLIdeSetup extends SMDSLStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new SMDSLRuntimeModule(), new SMDSLIdeModule()));
	}
	
}
