/*
 * generated by Xtext 2.30.0
 */
package org.thu.statemachine.textual.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class SMDSLUiModule extends AbstractSMDSLUiModule {

	public SMDSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
