/**
 * generated by Xtext 2.30.0
 */
package org.thu.statemachine.textual.sMDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Entry</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.thu.statemachine.textual.sMDSL.SMDSLPackage#getEntry()
 * @model
 * @generated
 */
public interface Entry extends EObject
{
} // Entry
