/**
 * generated by Xtext 2.30.0
 */
package org.thu.statemachine.textual.sMDSL;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>State</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.thu.statemachine.textual.sMDSL.State#getName <em>Name</em>}</li>
 *   <li>{@link org.thu.statemachine.textual.sMDSL.State#getContents <em>Contents</em>}</li>
 * </ul>
 *
 * @see org.thu.statemachine.textual.sMDSL.SMDSLPackage#getState()
 * @model
 * @generated
 */
public interface State extends Entry
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.thu.statemachine.textual.sMDSL.SMDSLPackage#getState_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.thu.statemachine.textual.sMDSL.State#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Contents</b></em>' containment reference list.
   * The list contents are of type {@link org.thu.statemachine.textual.sMDSL.Entry}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Contents</em>' containment reference list.
   * @see org.thu.statemachine.textual.sMDSL.SMDSLPackage#getState_Contents()
   * @model containment="true"
   * @generated
   */
  EList<Entry> getContents();

} // State
