/**
 * generated by Xtext 2.30.0
 */
package org.thu.statemachine.textual.sMDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Transition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.thu.statemachine.textual.sMDSL.Transition#getTo <em>To</em>}</li>
 * </ul>
 *
 * @see org.thu.statemachine.textual.sMDSL.SMDSLPackage#getTransition()
 * @model
 * @generated
 */
public interface Transition extends Entry
{
  /**
   * Returns the value of the '<em><b>To</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>To</em>' reference.
   * @see #setTo(State)
   * @see org.thu.statemachine.textual.sMDSL.SMDSLPackage#getTransition_To()
   * @model
   * @generated
   */
  State getTo();

  /**
   * Sets the value of the '{@link org.thu.statemachine.textual.sMDSL.Transition#getTo <em>To</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>To</em>' reference.
   * @see #getTo()
   * @generated
   */
  void setTo(State value);

} // Transition
