/*
 * generated by Xtext 2.30.0
 */
package org.thu.statemachine.textual.serializer;

import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;
import org.thu.statemachine.textual.sMDSL.SMDSLPackage;
import org.thu.statemachine.textual.sMDSL.State;
import org.thu.statemachine.textual.sMDSL.Transition;
import org.thu.statemachine.textual.services.SMDSLGrammarAccess;

@SuppressWarnings("all")
public class SMDSLSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private SMDSLGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == SMDSLPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case SMDSLPackage.STATE:
				sequence_State(context, (State) semanticObject); 
				return; 
			case SMDSLPackage.TRANSITION:
				sequence_Transition(context, (Transition) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * <pre>
	 * Contexts:
	 *     Entry returns State
	 *     State returns State
	 *
	 * Constraint:
	 *     (name=ID contents+=Entry*)
	 * </pre>
	 */
	protected void sequence_State(ISerializationContext context, State semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Entry returns Transition
	 *     Transition returns Transition
	 *
	 * Constraint:
	 *     to=[State|ID]
	 * </pre>
	 */
	protected void sequence_Transition(ISerializationContext context, Transition semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, SMDSLPackage.Literals.TRANSITION__TO) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, SMDSLPackage.Literals.TRANSITION__TO));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getTransitionAccess().getToStateIDTerminalRuleCall_2_0_1(), semanticObject.eGet(SMDSLPackage.Literals.TRANSITION__TO, false));
		feeder.finish();
	}
	
	
}
