/*
 * generated by Xtext 2.30.0
 */
package org.thu.statemachine.textual.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractSMDSLScopeProvider extends DelegatingScopeProvider {
}
