/*
 * generated by Xtext 2.30.0
 */
package org.thu.statemachine.textual;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class SMDSLStandaloneSetup extends SMDSLStandaloneSetupGenerated {

	public static void doSetup() {
		new SMDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
