/*
 * generated by Xtext 2.30.0
 */
package org.thu.statemachine.textual.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.thu.statemachine.textual.ui.internal.TextualActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SMDSLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(TextualActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		TextualActivator activator = TextualActivator.getInstance();
		return activator != null ? activator.getInjector(TextualActivator.ORG_THU_STATEMACHINE_TEXTUAL_SMDSL) : null;
	}

}
